### ISSUE TITLE
List of private data case numbers (n=217) 

### ISSUE THREAD

**Issue by chh105** [ababier/open-kbp#16]
Thanks for making such a large dataset available, and sorry if this is the wrong place to post questions (if there's some discussion forum I'm happy to post this there instead). I was wondering if it was possible to get a list of the case numbers for the 217 patients in the private dataset, which would exclude the public data (i.e. from TCIA) and the synthetic plans from plan augmentation.

**Comment by ababier** [comment]
I'm not sure if I fully understand your question, but this is a fine place to post it. The short answer is that I cannot provide those case numbers. All the data in the private dataset is clinical data from Princess Margaret Cancer Centre that I'm unable to release.

**Comment by chh105** [comment]
I guess to rephrase my question, it seems like you have already posted the private data + public data + augmented data in a randomized fashion. This is just my understanding based on reading your paper, so let me know if this is wrong. I was wondering if it was possible to get just the private data in the anonymized form that has already been posted. I would guess that the easiest way to do this would be to get a list of the folder names for those patients so that I can select and download the relevant csv files from github.

**Comment by ababier** [comment]
Oh sorry, I think there's a misunderstanding. The posted data only includes the "clean augmented public data". Does that clear things up?

**Comment by chh105** [comment]
Thanks for clarifying that it was augmented public data that was posted here. Sorry for the misunderstanding, and I'll go ahead and close this thread
