### ISSUE TITLE
Request for the original image dataset

### ISSUE THREAD

**Issue by HosseinShahverdi** [ababier/open-kbp#32]
Hey Aaron, Hope you are doing well.
Is it possible to access the original images you have converted to .csv files?
Thanks for your time.

**Comment by HosseinShahverdi** [comment]
Hey, thank you for your time and response.
We want to convert .csv files into the original format. So I wanted to have ground truth representations to know the dimensions of which and evaluate the accuracy of this conversion.
So now the data cannot be sharable. Please tell me in what dimension DICOM images are. Further, For example, a "ct" CSV file has 2 columns with 81256 rows, are these rows the flattened format of those pixels in N*M*P = 81256?

**Comment by ababier** [comment]
The original DICOM images did not have consistent dimensions. They had a range of different dimensions (e.g., 256x256 pixel slices, 512x512 pixel slices). The exact voxel dimensions vary across the patient cohort, but are provided in the dataset. 

The "ct" CSV files are _sparse_ representations of the CT image. In other words, they contain only non-zero CT values in one column and their corresponding _flattened_ coordinate in the other column. Every "ct" file maps to a 128x128x128 voxel tensor when d missing values (i.e., zeros) are populated in the tensor and the indices are unraveled into their x,y, and z coordinates. 

I'm unfamiliar with the acronym NMP, but if you explain it I may be able to better answer your question

**Comment by JSBuatti** [comment]
Hi Aaron,
I have a similar question to Hosein. I am looking for the full-resolution CT dicoms for each of the patients in the KBP dataset. Are you able to provide the TCIA DICOMS? Or, do you have a key between the original KBP and TCIA names (i.e. pt_001 = HNSCC-01-0001)? If that were available, I could see about downloading the TCIA DICOMS on my own. 

Thanks for your help!

**Comment by ababier** [comment]
We no longer have the key between the TCIA file names and the OpenKBP patient IDs.
